---
abstract: 'Perl extention to do something'
author:
  - 'Fuji, Goro <fuji.goro@dena.jp>'
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  File::chdir: 0
  LWP::Simple: 0
  Module::Build: 0
  Probe::Perl: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-RRDtool
no_index:
  directory:
    - x
provides:
  Alien::RRDtool:
    file: lib/Alien/RRDtool.pm
    version: 0.01
requires:
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
